# 基本設定
CONFIG_ZMK_KEYBOARD_NAME="Dactyl Ball46"

# マトリックス・入力
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

# PMW3610ドライバー（badjeff版）
CONFIG_PMW3610_ALT=y

# 無線関連（必要に応じて）
CONFIG_BT=y
CONFIG_ZMK_BLE=y

# バッテリー残量表示を使いたい場合（任意）
# CONFIG_ZMK_BATTERY_REPORTING=y
